var runcodesApp=angular.module("runcodesApp",["angular-rickshaw","angular-flot"]);runcodesApp.constant("moment",moment);
runcodesApp.controller("ServerTimeController",["$scope","$sce","$interval","ServerTimeService",function(a,b,c,d){a.serverTime={};a.serverTime.datetime={};a.serverTime.date="--";a.serverTime.time="--";a.serverTime.datetime.seconds=100;a.lastRequest=301;a.runningRequest=0;a.updateServerTime=c(function(){59<=parseInt(a.serverTime.datetime.minutes)&&59<=parseInt(a.serverTime.datetime.seconds)||300<a.lastRequest&&0==a.runningRequest?(a.runningRequest++,d.loadServerTime().then(function(b){a.serverTime.datetime=
b;a.lastRequest=0;a.runningRequest=0})):(a.serverTime.datetime.seconds=parseInt(a.serverTime.datetime.seconds)+1,59<parseInt(a.serverTime.datetime.seconds)&&(a.serverTime.datetime.seconds=0,a.serverTime.datetime.minutes=parseInt(a.serverTime.datetime.minutes)+1,a.serverTime.datetime.minutes=10>a.serverTime.datetime.minutes?"0"+a.serverTime.datetime.minutes:""+a.serverTime.datetime.minutes),a.serverTime.datetime.seconds=10>a.serverTime.datetime.seconds?"0"+a.serverTime.datetime.seconds:""+a.serverTime.datetime.seconds,
a.lastRequest++);isNaN(a.serverTime.datetime.mday)||(a.serverTime.date=a.serverTime.datetime.mday+"/"+a.serverTime.datetime.mon+"/"+a.serverTime.datetime.year,a.serverTime.time=a.serverTime.datetime.hours+":"+a.serverTime.datetime.minutes+":"+a.serverTime.datetime.seconds)},1E3);a.initializeServerTime=function(b,c){a.serverTime.date=b;a.serverTime.time=c}}]);runcodesApp.service("ServerTimeService",["$http",function(a){this.loadServerTime=function(){return a.post("/getServerDateTimeJson").then(function(a){return a.data})}}]);
runcodesApp.controller("OfferingStatsController",["$scope","$sce","$interval","StatsService",function(a,b,c,d){a.offeringInfographic={};a.offeringInfographic.students=0;a.offeringInfographic.gradespect=0;a.offeringInfographic.gradesavg=0;a.student=-1;a.dataset=[{data:[],yaxis:1,label:""}];a.options={legend:{container:"#legend",show:!0},bars:{show:!0,barWidth:.6,align:"center"},colors:["#FFFFFF"],xaxis:{min:0},yaxis:{min:0,max:10,ticks:10}};a.loadOfferingStats=function(b){d.loadOfferingChartData(b,
a.student).then(function(b){a.dataset=[{data:[],yaxis:1,label:""}];a.options.xaxis.ticks=b.labelsX;a.options.xaxis.max=b.labelsX.length+1;a.options.colors=b.colors;a.dataset[0].data=b.series[0].data;a.dataset[0].label=b.series[0].name;void 0!==b.series[1]&&(a.dataset[1]={},a.dataset[1].data=b.series[1].data,a.dataset[1].label=b.series[1].name,a.dataset[1].lines={show:!0},a.dataset[1].bars={show:!1})})};a.loadOfferingInfographicData=function(b){d.loadOfferingInfographicData(b).then(function(b){a.offeringInfographic=
b})}}]);
runcodesApp.service("StatsService",["$http",function(a){function b(a){return a.data}this.loadCommitsChartData=function(){return a.post("/Stats/commitsChart").then(b)};this.loadVisitsChartData=function(){return a.post("/Stats/visitsChart").then(b)};this.loadDiskChartData=function(){return a.post("/Stats/diskChart").then(b)};this.loadCommitsInfographicData=function(){return a.post("/Stats/commitsInfographic").then(b)};this.loadHomeInfographicData=function(){return a.post("/Stats/homeInfographic").then(b)};this.loadHomeServersData=
function(){return a.post("/Stats/homeServers").then(b)};this.loadOfferingChartData=function(c,d){return a.post("/Offerings/stats/"+c+"/"+d).then(b)};this.loadOfferingInfographicData=function(c){return a.post("/Offerings/infographic/"+c).then(b)}}]);
runcodesApp.controller("CommitController",["$scope","$sce","$interval","StatsService",function(a,b,c,d){a.filename="";a.showFileInfo=!1;a.progress=0;a.data=null;a.submitted=!1;a.submitFile=function(){a.submitted=!0;a.submitButton="Uploading...";a.data.submit()};a.loadFileUpload=function(b){$("#userFileUpload").fileupload({dataType:"json",url:"/Exercises/commit/"+b,autoUpload:!1,dropZone:"body",add:function(b,c){a.alertMessage=!1;a.showFileInfo=!0;a.filename=c.files[0].name+" - "+c.files[0].size+" bytes";
a.data=c},start:function(a,b){},fail:function(a,b){alert("Ocorreu uma falha e seu arquivo n\u00e3o foi enviado, por favor tente novamente");location.reload(!0)},progressall:function(b,c){var d=parseInt(c.loaded/c.total*100,10);a.progress=d},done:function(b,c){c.result.files[0].error?(a.alertMessage=c.result.files[0].error,a.filename="",a.showFileInfo=!1,a.progress=0,a.data=null,a.submitted=!1,a.submitButton=a.submitButtonDefault):(a.submitButton=a.submitButtonReloading,location.reload(!0))}})}}]);
runcodesApp.service("CommitsExerciseCasesService",["$http",function(a){this.loadCommitExerciseCase=function(b){return a.post("/CommitsExerciseCases/viewCase/"+b).then(function(a){return a.data})}}]);runcodesApp.controller("ExerciseCasesController",["$scope","$sce","CommitsExerciseCasesService",function(a,b,c){a.caseId=-1;a.loadCase=function(){a.commitsExerciseCaseView=b.trustAsHtml("<p>Carregando</p>");-1!=a.caseId&&c.loadCommitExerciseCase(a.caseId).then(function(c){a.commitsExerciseCaseView=b.trustAsHtml(c)})}}]);
runcodesApp.controller("GradesController",["$scope",function(a){a.notDelivered="0.0"}]);
runcodesApp.controller("MultipleUploadController",["$scope",function(a){a.progress=0;a.files=[];a.addExistentFile=function(b,c,d){a.files.push({existent:!0,realname:b,size:d,id:c,remove:!1})};a.removeExistentFile=function(b){a.files[b].remove=!0};a.undoRemoveExistentFile=function(b){a.files[b].remove=!1};a.removeFile=function(b){a.files.splice(b,1)};a.loadFileUpload=function(b,c){c=c||"#files-drop-zone";$(b).fileupload({dataType:"json",dropZone:$(c),add:function(a,b){b.submit()},start:function(a,
b){},fail:function(a,b){alert("Ocorreu uma falha e seu arquivo n\u00e3o foi enviado, por favor tente novamente")},progressall:function(b,c){var f=parseInt(c.loaded/c.total*100,10);a.uploadMessage=a.uploadingText+" ("+f+"%)";a.progress=f},done:function(b,c){$.each(c.result.files,function(b,c){c.error||(a.files.push(c),a.progress=0)});a.uploadMessage=a.uploadText}})}}]);
runcodesApp.controller("FormExerciseController",["$scope","FormExerciseService",function(a,b){a.allowedFiles=[];a.loading=!1;var c=!0;$(".chosen-select").chosen({width:"100%"});a.reloadFileTypes=function(){a.loading=!0;b.loadAllowedFilesByType(a.filesType).then(function(b){a.allowedFiles=b;c&&(c=!1,setTimeout(function(){$(".chosen-select").val(a.initSelection)},10));setTimeout(function(){$(".chosen-select").trigger("chosen:updated");a.loading=!1},500)})}}]);
runcodesApp.service("FormExerciseService",["$http",function(a){this.loadAllowedFilesByType=function(b){return a.post("/AllowedFiles/getAllowedFilesList/"+b).then(function(a){return a.data})}}]);runcodesApp.controller("FormOfferingController",["$scope","FormOfferingService",function(a,b){a.coursesList=[];a.searchString="";a.loading=!1;a.loadCourses=function(){a.loading=!0;a.showCourses=!0;b.loadCoursesWithSearchString(a.searchString).then(function(b){a.coursesList=b;a.loading=!1;a.showCourses=!0})}}]);
runcodesApp.service("FormOfferingService",["$http",function(a){this.loadCoursesWithSearchString=function(b){return a.post("/Courses/coursesList/"+b).then(function(a){return a.data})}}]);runcodesApp.controller("FormExerciseCaseController",["$scope",function(a){}]);runcodesApp.controller("FormProfileController",["$scope","FormProfileService",function(a,b){a.loadUniversityInfo=function(){b.loadUniversityIdentifierText(a.university).then(function(b){a.identifierText=b})}}]);
runcodesApp.service("FormProfileService",["$http",function(a){this.loadUniversityIdentifierText=function(b){return a.post("/Universities/getIdentifierText/"+b).then(function(a){return a.data})}}]);
runcodesApp.controller("ExerciseProfessorViewController",["$scope","$sce","ExerciseProfessorViewService",function(a,b,c){a.loading=!1;a.dataset=[{data:[],yaxis:1,label:""}];a.options={legend:{container:"#legend",show:!0},bars:{show:!0,barWidth:.6,align:"center"},colors:["#FFFFFF"],xaxis:{min:0},yaxis:{min:0,max:101,ticks:10}};a.loadCasesStats=function(){c.loadCaseChartData(a.exercise).then(function(b){a.dataset[0].data=b.series[0].data;a.dataset[0].label=b.series[0].name;a.options.xaxis.ticks=b.labelsX;
a.options.xaxis.max=b.labelsX.length+1;a.options.colors=b.colors})};a.loadStudentCommits=function(){-1==a.studentCommits?a.studentCommitsContent=b.trustAsHtml(""):(a.loading=!0,c.loadStudentCommitsInfo(a.exercise,a.studentCommits).then(function(c){a.studentCommitsContent=b.trustAsHtml(c);a.loading=!1}))}}]);
runcodesApp.service("ExerciseProfessorViewService",["$http",function(a){function b(a){return a.data}this.loadStudentCommitsInfo=function(c,d){return a.post("/Exercises/participantCommits/"+c+"/"+d).then(b)};this.loadCaseChartData=function(c){return a.post("/Exercises/stats/"+c).then(b)}}]);
runcodesApp.controller("OfferingController",["$scope","$sce","OfferingService",function(a,b,c){a.professorsAndAssistants=[];a.loading=!1;a.setProfessor=function(){a.loading=!0;c.setUserAsProfessor(a.offeringId,a.participant).then(function(){a.loadProfessorsAndAssistantsTable()})};a.setAssistant=function(){a.loading=!0;c.setUserAsAssistant(a.offeringId,a.participant).then(function(){a.loadProfessorsAndAssistantsTable()})};a.setStudent=function(b){a.loading=!0;c.setUserAsStudent(a.offeringId,b).then(function(){a.loadProfessorsAndAssistantsTable()})};
a.loadProfessorsAndAssistantsTable=function(){c.loadProfessorsAndAssistants(a.offeringId).then(function(b){a.professorsAndAssistants=b;a.loading=!1})}}]);
runcodesApp.service("OfferingService",["$http",function(a){function b(a){return a.data}this.setUserAsAssistant=function(c,d){return a.post("/Offerings/setAssistant/"+c+"/"+d).then(b)};this.setUserAsProfessor=function(c,d){return a.post("/Offerings/setProfessor/"+c+"/"+d).then(b)};this.setUserAsStudent=function(c,d){return a.post("/Offerings/setStudent/"+c+"/"+d).then(b)};this.loadProfessorsAndAssistants=function(c){return a.post("/Offerings/getProfessorsAndAssistantsList/"+c).then(b)}}]);
runcodesApp.controller("LastCommitController",["$scope","$sce","$timeout","LastCommitService",function(a,b,c,d){function e(){d.loadCommitCases(a.commit.id).then(function(c){a.commitsExerciseCaseDetails=b.trustAsHtml(c)})}a.professorsAndAssistants=[];a.loading=!1;a.count=0;a.commitsExerciseCaseDetails=b.trustAsHtml("");a.startRefreshing=function(){4>a.commit.status.value&&(a.loading=!0,c(function(){d.loadCommitInfo(a.commit.id).then(function(b){a.commit=b.commit;4>b.commit.status.value?a.startRefreshing():
(4!=b.commit.status.value&&5!=b.commit.status.value||e(),a.loading=!1)})},2E3))}}]);runcodesApp.service("LastCommitService",["$http",function(a){function b(a){return a.data}this.loadCommitInfo=function(c){return a.post("/Commits/commitInfo/"+c).then(b)};this.loadCommitCases=function(c){return a.post("/Commits/casesInfo/"+c).then(b)}}]);
runcodesApp.controller("MultipleSimilarityTestController",["$scope","$sce","$timeout","MultipleSimilarityService","moment",function(a,b,c,d,e){a.offering=0;a.selectedExercise=0;a.exercises=[];a.selectedExercises=[];a.moment=e;a.formatDate=function(a){return(new e(a,"YYYY-MM-DD HH:mm:ss")).format("DD/MM/YYYY HH:mm:ss")};a.updateExercisesList=function(){a.exercises=[];a.selectedExercise=0;d.loadExercisesList(a.offering).then(function(b){a.exercises=b;a.selectedExercise=0})};a.addExercise=function(){a.selectedExercises.push(a.exercises[a.selectedExercise])};
a.removeExercise=function(b){a.selectedExercises.splice(b,1)}}]);runcodesApp.service("MultipleSimilarityService",["$http",function(a){function b(a){return a.data}this.loadExercisesList=function(c){return a.post("/Offerings/listExercises/"+c).then(b)}}]);
$(document).ready(function(){moment.locale("pt-br");$(".dropdown").on("show.bs.dropdown",function(a){$(this).find(".dropdown-menu").first().stop(!0,!0).slideDown()});$(".dropdown").on("hide.bs.dropdown",function(a){$(this).find(".dropdown-menu").first().stop(!0,!0).slideUp()});$('[data-toggle="tooltip"]').tooltip();$(".summernote").summernote();$(".chosen-unique-select").chosen({width:"100%"});$(".datepicker").datetimepicker({format:"DD/MM/YYYY",showTodayButton:!1,icons:{time:"fa fa-clock-o",date:"fa fa-calendar",
up:"fa fa-chevron-up",down:"fa fa-chevron-down",previous:"fa fa-chevron-left",next:"fa fa-chevron-right",today:"fa fa-calendar-o",clear:"fa fa-eraser"}});$(".datetimepicker").datetimepicker({format:"DD/MM/YYYY HH:mm:ss",sideBySide:!0,showTodayButton:!0,icons:{time:"fa fa-clock-o",date:"fa fa-calendar",up:"fa fa-chevron-up",down:"fa fa-chevron-down",previous:"fa fa-chevron-left",next:"fa fa-chevron-right",today:"fa fa-calendar-o",clear:"fa fa-eraser"}});hljs.initHighlightingOnLoad();$(".btn-hide-panel").on("click",
function(){var a=$(this).attr("data-panel");$("#panel-"+a).animate({height:0,padding:0},700,function(){$.getJSON("/cookies/hidePanel/"+a);$("#btn-hide-"+a).hide();$("#btn-show-"+a).show()})});$(".btn-show-panel").on("click",function(){var a=$(this).attr("data-panel"),c=$("#panel-"+a).height(),d=$("#panel-"+a).css("height","auto").height();"home-stats"==a&&(d=310);"home-servers"==a&&(d+=20);$("#panel-"+a).height(c).animate({height:d,padding:10},700,function(){$.getJSON("/cookies/showPanel/"+a);$("#btn-hide-"+
a).show();$("#btn-show-"+a).hide()})});$(".btn-toggle-panel").on("click",function(a){a.preventDefault();var c=$(this).attr("data-panel");if($("#panel-"+c).hasClass("panel-hide")){$("#panel-"+c).removeClass("panel-hide");a=$("#panel-"+c).height();var d=$("#panel-"+c).css("height","auto").height();$("#panel-"+c).height(a).animate({height:d,padding:10},700)}else $("#panel-"+c).animate({height:0,padding:0},700,function(){$("#panel-"+c).addClass("panel-hide")})});if(window.addEventListener){var a=[];window.addEventListener("keydown",
function(b){a.push(b.keyCode);0<=a.toString().indexOf("38,38,40,40,37,39,37,39,66,65")&&(console.log("Konami"),a=[]);(37>b.keyCode||40<b.keyCode)&&66!=b.keyCode&&65!=b.keyCode&&(a=[])},!0)}$(".main-loading").addClass("hidden");$(".main-content").removeClass("hidden");$("#nav-right-menu").removeClass("hidden")});
